insert into tb_category (name, created_At) values ('Books', NOW());
insert into tb_category (name, created_At) values ('Electronics', NOW());
insert into tb_category (name) values ('Computers');
insert into tb_category (name, created_At) values ('Books', NOW());
insert into tb_category (name, created_At) values ('Electronics', NOW());
insert into tb_category (name) values ('Computers');
insert into tb_category (name, created_At) values ('Books', NOW());
insert into tb_category (name, created_At) values ('Electronics', NOW());
insert into tb_category (name) values ('Computers');
insert into tb_category (name, created_At) values ('Books', NOW());
insert into tb_category (name, created_At) values ('Electronics', NOW());
insert into tb_category (name) values ('Computers');
insert into tb_category (name, created_At) values ('Books', NOW());
insert into tb_category (name, created_At) values ('Electronics', NOW());
insert into tb_category (name) values ('Computers');
insert into tb_category (name, created_At) values ('Books', NOW());
insert into tb_category (name, created_At) values ('Electronics', NOW());
insert into tb_category (name) values ('Computers');
insert into tb_category (name, created_At) values ('Books', NOW());
insert into tb_category (name, created_At) values ('Electronics', NOW());
insert into tb_category (name) values ('Computers');
insert into tb_category (name, created_At) values ('Books', NOW());
insert into tb_category (name, created_At) values ('Electronics', NOW());
insert into tb_category (name) values ('Computers');
insert into tb_category (name, created_At) values ('Books', NOW());
insert into tb_category (name, created_At) values ('Electronics', NOW());
insert into tb_category (name) values ('Computers');
insert into tb_category (name, created_At) values ('Books', NOW());
insert into tb_category (name, created_At) values ('Electronics', NOW());
insert into tb_category (name) values ('Computers');
insert into tb_category (name, created_At) values ('Books', NOW());
insert into tb_category (name, created_At) values ('Electronics', NOW());
insert into tb_category (name) values ('Computers');
insert into tb_category (name, created_At) values ('Books', NOW());
insert into tb_category (name, created_At) values ('Electronics', NOW());
insert into tb_category (name) values ('Computers');
insert into tb_category (name, created_At) values ('Books', NOW());
insert into tb_category (name, created_At) values ('Electronics', NOW());
insert into tb_category (name) values ('Computers');
insert into tb_category (name, created_At) values ('Books', NOW());
insert into tb_category (name, created_At) values ('Electronics', NOW());
insert into tb_category (name) values ('Computers');
insert into tb_category (name, created_At) values ('Books', NOW());
insert into tb_category (name, created_At) values ('Electronics', NOW());
insert into tb_category (name) values ('Computers');
insert into tb_category (name, created_At) values ('Books', NOW());
insert into tb_category (name, created_At) values ('Electronics', NOW());
insert into tb_category (name) values ('Computers');
